import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
    <div >
      <Head>
        <title>HoodieHub.com - Where Fashion Meets Comfort</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      hey this is codeswear
      <div className='mx-4 bg-slate-500'>this is me</div>
    </div>
  )
}
